export const SETUP_WIZARD_AUTO_ADVANCE_DELAY_MS = 800
export const SETUP_WIZARD_COPY_RESET_DELAY_MS = 2000
export const SETUP_WIZARD_FIREWALL_POLL_INTERVAL_MS = 1000
export const SETUP_WIZARD_FIREWALL_POLL_MAX_ATTEMPTS = 10
